/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as AnggotaIndexRouteImport } from './app/anggota/index'
import { Route as CariIndexRouteImport } from './app/cari/index'
import { Route as PengaturanIndexRouteImport } from './app/pengaturan/index'
import { Route as AnggotaIdIndexRouteImport } from './app/anggota/$id/index'
import { Route as AnggotaIdEditRouteImport } from './app/anggota/$id/edit'
import { Route as AnggotaBarcodeIdRouteImport } from './app/anggota/barcode/$id'
import { Route as AnggotaTambahIndexRouteImport } from './app/anggota/tambah/index'
import { Route as AnggotaIdPengukuranPengukuranIdRouteImport } from './app/anggota/$id/pengukuran/$pengukuranId'
import { Route as AnggotaIdPengukuranTambahRouteImport } from './app/anggota/$id/pengukuran/tambah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIndexRoute = AnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => rootRouteImport,
} as any)
const CariIndexRoute = CariIndexRouteImport.update({
  id: '/cari/',
  path: '/cari/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanIndexRoute = PengaturanIndexRouteImport.update({
  id: '/pengaturan/',
  path: '/pengaturan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIdIndexRoute = AnggotaIdIndexRouteImport.update({
  id: '/anggota/$id/',
  path: '/anggota/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIdEditRoute = AnggotaIdEditRouteImport.update({
  id: '/anggota/$id/edit',
  path: '/anggota/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaBarcodeIdRoute = AnggotaBarcodeIdRouteImport.update({
  id: '/anggota/barcode/$id',
  path: '/anggota/barcode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaTambahIndexRoute = AnggotaTambahIndexRouteImport.update({
  id: '/anggota/tambah/',
  path: '/anggota/tambah/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIdPengukuranPengukuranIdRoute =
  AnggotaIdPengukuranPengukuranIdRouteImport.update({
    id: '/anggota/$id/pengukuran/$pengukuranId',
    path: '/anggota/$id/pengukuran/$pengukuranId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnggotaIdPengukuranTambahRoute =
  AnggotaIdPengukuranTambahRouteImport.update({
    id: '/anggota/$id/pengukuran/tambah',
    path: '/anggota/$id/pengukuran/tambah',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/cari/': typeof CariIndexRoute
  '/pengaturan/': typeof PengaturanIndexRoute
  '/anggota/$id/edit': typeof AnggotaIdEditRoute
  '/anggota/barcode/$id': typeof AnggotaBarcodeIdRoute
  '/anggota/$id/': typeof AnggotaIdIndexRoute
  '/anggota/tambah/': typeof AnggotaTambahIndexRoute
  '/anggota/$id/pengukuran/$pengukuranId': typeof AnggotaIdPengukuranPengukuranIdRoute
  '/anggota/$id/pengukuran/tambah': typeof AnggotaIdPengukuranTambahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaIndexRoute
  '/cari': typeof CariIndexRoute
  '/pengaturan': typeof PengaturanIndexRoute
  '/anggota/$id/edit': typeof AnggotaIdEditRoute
  '/anggota/barcode/$id': typeof AnggotaBarcodeIdRoute
  '/anggota/$id': typeof AnggotaIdIndexRoute
  '/anggota/tambah': typeof AnggotaTambahIndexRoute
  '/anggota/$id/pengukuran/$pengukuranId': typeof AnggotaIdPengukuranPengukuranIdRoute
  '/anggota/$id/pengukuran/tambah': typeof AnggotaIdPengukuranTambahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/cari/': typeof CariIndexRoute
  '/pengaturan/': typeof PengaturanIndexRoute
  '/anggota/$id/edit': typeof AnggotaIdEditRoute
  '/anggota/barcode/$id': typeof AnggotaBarcodeIdRoute
  '/anggota/$id/': typeof AnggotaIdIndexRoute
  '/anggota/tambah/': typeof AnggotaTambahIndexRoute
  '/anggota/$id/pengukuran/$pengukuranId': typeof AnggotaIdPengukuranPengukuranIdRoute
  '/anggota/$id/pengukuran/tambah': typeof AnggotaIdPengukuranTambahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anggota/'
    | '/cari/'
    | '/pengaturan/'
    | '/anggota/$id/edit'
    | '/anggota/barcode/$id'
    | '/anggota/$id/'
    | '/anggota/tambah/'
    | '/anggota/$id/pengukuran/$pengukuranId'
    | '/anggota/$id/pengukuran/tambah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anggota'
    | '/cari'
    | '/pengaturan'
    | '/anggota/$id/edit'
    | '/anggota/barcode/$id'
    | '/anggota/$id'
    | '/anggota/tambah'
    | '/anggota/$id/pengukuran/$pengukuranId'
    | '/anggota/$id/pengukuran/tambah'
  id:
    | '__root__'
    | '/'
    | '/anggota/'
    | '/cari/'
    | '/pengaturan/'
    | '/anggota/$id/edit'
    | '/anggota/barcode/$id'
    | '/anggota/$id/'
    | '/anggota/tambah/'
    | '/anggota/$id/pengukuran/$pengukuranId'
    | '/anggota/$id/pengukuran/tambah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnggotaIndexRoute: typeof AnggotaIndexRoute
  CariIndexRoute: typeof CariIndexRoute
  PengaturanIndexRoute: typeof PengaturanIndexRoute
  AnggotaIdEditRoute: typeof AnggotaIdEditRoute
  AnggotaBarcodeIdRoute: typeof AnggotaBarcodeIdRoute
  AnggotaIdIndexRoute: typeof AnggotaIdIndexRoute
  AnggotaTambahIndexRoute: typeof AnggotaTambahIndexRoute
  AnggotaIdPengukuranPengukuranIdRoute: typeof AnggotaIdPengukuranPengukuranIdRoute
  AnggotaIdPengukuranTambahRoute: typeof AnggotaIdPengukuranTambahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/': {
      id: '/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AnggotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari/': {
      id: '/cari/'
      path: '/cari'
      fullPath: '/cari/'
      preLoaderRoute: typeof CariIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/': {
      id: '/pengaturan/'
      path: '/pengaturan'
      fullPath: '/pengaturan/'
      preLoaderRoute: typeof PengaturanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/$id/': {
      id: '/anggota/$id/'
      path: '/anggota/$id'
      fullPath: '/anggota/$id/'
      preLoaderRoute: typeof AnggotaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/$id/edit': {
      id: '/anggota/$id/edit'
      path: '/anggota/$id/edit'
      fullPath: '/anggota/$id/edit'
      preLoaderRoute: typeof AnggotaIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/barcode/$id': {
      id: '/anggota/barcode/$id'
      path: '/anggota/barcode/$id'
      fullPath: '/anggota/barcode/$id'
      preLoaderRoute: typeof AnggotaBarcodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/tambah/': {
      id: '/anggota/tambah/'
      path: '/anggota/tambah'
      fullPath: '/anggota/tambah/'
      preLoaderRoute: typeof AnggotaTambahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/$id/pengukuran/$pengukuranId': {
      id: '/anggota/$id/pengukuran/$pengukuranId'
      path: '/anggota/$id/pengukuran/$pengukuranId'
      fullPath: '/anggota/$id/pengukuran/$pengukuranId'
      preLoaderRoute: typeof AnggotaIdPengukuranPengukuranIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/$id/pengukuran/tambah': {
      id: '/anggota/$id/pengukuran/tambah'
      path: '/anggota/$id/pengukuran/tambah'
      fullPath: '/anggota/$id/pengukuran/tambah'
      preLoaderRoute: typeof AnggotaIdPengukuranTambahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnggotaIndexRoute: AnggotaIndexRoute,
  CariIndexRoute: CariIndexRoute,
  PengaturanIndexRoute: PengaturanIndexRoute,
  AnggotaIdEditRoute: AnggotaIdEditRoute,
  AnggotaBarcodeIdRoute: AnggotaBarcodeIdRoute,
  AnggotaIdIndexRoute: AnggotaIdIndexRoute,
  AnggotaTambahIndexRoute: AnggotaTambahIndexRoute,
  AnggotaIdPengukuranPengukuranIdRoute: AnggotaIdPengukuranPengukuranIdRoute,
  AnggotaIdPengukuranTambahRoute: AnggotaIdPengukuranTambahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
