/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as AkunIndexRouteImport } from './app/akun/index'
import { Route as AnggotaIndexRouteImport } from './app/anggota/index'
import { Route as AnggotaIdRouteImport } from './app/anggota/$id'
import { Route as CariIndexRouteImport } from './app/cari/index'
import { Route as AnggotaIdEditRouteImport } from './app/anggota/$id/edit'
import { Route as AnggotaBarcodeIdRouteImport } from './app/anggota/barcode/$id'
import { Route as AnggotaTambahIndexRouteImport } from './app/anggota/tambah/index'
import { Route as AnggotaIdPengukuranPengukuranIdRouteImport } from './app/anggota/$id/pengukuran/$pengukuranId'
import { Route as AnggotaIdPengukuranTambahRouteImport } from './app/anggota/$id/pengukuran/tambah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunIndexRoute = AkunIndexRouteImport.update({
  id: '/akun/',
  path: '/akun/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIndexRoute = AnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIdRoute = AnggotaIdRouteImport.update({
  id: '/anggota/$id',
  path: '/anggota/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CariIndexRoute = CariIndexRouteImport.update({
  id: '/cari/',
  path: '/cari/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIdEditRoute = AnggotaIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AnggotaIdRoute,
} as any)
const AnggotaBarcodeIdRoute = AnggotaBarcodeIdRouteImport.update({
  id: '/anggota/barcode/$id',
  path: '/anggota/barcode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaTambahIndexRoute = AnggotaTambahIndexRouteImport.update({
  id: '/anggota/tambah/',
  path: '/anggota/tambah/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIdPengukuranPengukuranIdRoute =
  AnggotaIdPengukuranPengukuranIdRouteImport.update({
    id: '/pengukuran/$pengukuranId',
    path: '/pengukuran/$pengukuranId',
    getParentRoute: () => AnggotaIdRoute,
  } as any)
const AnggotaIdPengukuranTambahRoute =
  AnggotaIdPengukuranTambahRouteImport.update({
    id: '/pengukuran/tambah',
    path: '/pengukuran/tambah',
    getParentRoute: () => AnggotaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anggota/$id': typeof AnggotaIdRouteWithChildren
  '/akun/': typeof AkunIndexRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/cari/': typeof CariIndexRoute
  '/anggota/$id/edit': typeof AnggotaIdEditRoute
  '/anggota/barcode/$id': typeof AnggotaBarcodeIdRoute
  '/anggota/tambah/': typeof AnggotaTambahIndexRoute
  '/anggota/$id/pengukuran/$pengukuranId': typeof AnggotaIdPengukuranPengukuranIdRoute
  '/anggota/$id/pengukuran/tambah': typeof AnggotaIdPengukuranTambahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anggota/$id': typeof AnggotaIdRouteWithChildren
  '/akun': typeof AkunIndexRoute
  '/anggota': typeof AnggotaIndexRoute
  '/cari': typeof CariIndexRoute
  '/anggota/$id/edit': typeof AnggotaIdEditRoute
  '/anggota/barcode/$id': typeof AnggotaBarcodeIdRoute
  '/anggota/tambah': typeof AnggotaTambahIndexRoute
  '/anggota/$id/pengukuran/$pengukuranId': typeof AnggotaIdPengukuranPengukuranIdRoute
  '/anggota/$id/pengukuran/tambah': typeof AnggotaIdPengukuranTambahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anggota/$id': typeof AnggotaIdRouteWithChildren
  '/akun/': typeof AkunIndexRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/cari/': typeof CariIndexRoute
  '/anggota/$id/edit': typeof AnggotaIdEditRoute
  '/anggota/barcode/$id': typeof AnggotaBarcodeIdRoute
  '/anggota/tambah/': typeof AnggotaTambahIndexRoute
  '/anggota/$id/pengukuran/$pengukuranId': typeof AnggotaIdPengukuranPengukuranIdRoute
  '/anggota/$id/pengukuran/tambah': typeof AnggotaIdPengukuranTambahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anggota/$id'
    | '/akun/'
    | '/anggota/'
    | '/cari/'
    | '/anggota/$id/edit'
    | '/anggota/barcode/$id'
    | '/anggota/tambah/'
    | '/anggota/$id/pengukuran/$pengukuranId'
    | '/anggota/$id/pengukuran/tambah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anggota/$id'
    | '/akun'
    | '/anggota'
    | '/cari'
    | '/anggota/$id/edit'
    | '/anggota/barcode/$id'
    | '/anggota/tambah'
    | '/anggota/$id/pengukuran/$pengukuranId'
    | '/anggota/$id/pengukuran/tambah'
  id:
    | '__root__'
    | '/'
    | '/anggota/$id'
    | '/akun/'
    | '/anggota/'
    | '/cari/'
    | '/anggota/$id/edit'
    | '/anggota/barcode/$id'
    | '/anggota/tambah/'
    | '/anggota/$id/pengukuran/$pengukuranId'
    | '/anggota/$id/pengukuran/tambah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnggotaIdRoute: typeof AnggotaIdRouteWithChildren
  AkunIndexRoute: typeof AkunIndexRoute
  AnggotaIndexRoute: typeof AnggotaIndexRoute
  CariIndexRoute: typeof CariIndexRoute
  AnggotaBarcodeIdRoute: typeof AnggotaBarcodeIdRoute
  AnggotaTambahIndexRoute: typeof AnggotaTambahIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/': {
      id: '/akun/'
      path: '/akun'
      fullPath: '/akun/'
      preLoaderRoute: typeof AkunIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/': {
      id: '/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AnggotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/$id': {
      id: '/anggota/$id'
      path: '/anggota/$id'
      fullPath: '/anggota/$id'
      preLoaderRoute: typeof AnggotaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari/': {
      id: '/cari/'
      path: '/cari'
      fullPath: '/cari/'
      preLoaderRoute: typeof CariIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/$id/edit': {
      id: '/anggota/$id/edit'
      path: '/edit'
      fullPath: '/anggota/$id/edit'
      preLoaderRoute: typeof AnggotaIdEditRouteImport
      parentRoute: typeof AnggotaIdRoute
    }
    '/anggota/barcode/$id': {
      id: '/anggota/barcode/$id'
      path: '/anggota/barcode/$id'
      fullPath: '/anggota/barcode/$id'
      preLoaderRoute: typeof AnggotaBarcodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/tambah/': {
      id: '/anggota/tambah/'
      path: '/anggota/tambah'
      fullPath: '/anggota/tambah/'
      preLoaderRoute: typeof AnggotaTambahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/$id/pengukuran/$pengukuranId': {
      id: '/anggota/$id/pengukuran/$pengukuranId'
      path: '/pengukuran/$pengukuranId'
      fullPath: '/anggota/$id/pengukuran/$pengukuranId'
      preLoaderRoute: typeof AnggotaIdPengukuranPengukuranIdRouteImport
      parentRoute: typeof AnggotaIdRoute
    }
    '/anggota/$id/pengukuran/tambah': {
      id: '/anggota/$id/pengukuran/tambah'
      path: '/pengukuran/tambah'
      fullPath: '/anggota/$id/pengukuran/tambah'
      preLoaderRoute: typeof AnggotaIdPengukuranTambahRouteImport
      parentRoute: typeof AnggotaIdRoute
    }
  }
}

interface AnggotaIdRouteChildren {
  AnggotaIdEditRoute: typeof AnggotaIdEditRoute
  AnggotaIdPengukuranPengukuranIdRoute: typeof AnggotaIdPengukuranPengukuranIdRoute
  AnggotaIdPengukuranTambahRoute: typeof AnggotaIdPengukuranTambahRoute
}

const AnggotaIdRouteChildren: AnggotaIdRouteChildren = {
  AnggotaIdEditRoute: AnggotaIdEditRoute,
  AnggotaIdPengukuranPengukuranIdRoute: AnggotaIdPengukuranPengukuranIdRoute,
  AnggotaIdPengukuranTambahRoute: AnggotaIdPengukuranTambahRoute,
}

const AnggotaIdRouteWithChildren = AnggotaIdRoute._addFileChildren(
  AnggotaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnggotaIdRoute: AnggotaIdRouteWithChildren,
  AkunIndexRoute: AkunIndexRoute,
  AnggotaIndexRoute: AnggotaIndexRoute,
  CariIndexRoute: CariIndexRoute,
  AnggotaBarcodeIdRoute: AnggotaBarcodeIdRoute,
  AnggotaTambahIndexRoute: AnggotaTambahIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
