/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as AkunIndexRouteImport } from './app/akun/index'
import { Route as AnggotaIndexRouteImport } from './app/anggota/index'
import { Route as CariIndexRouteImport } from './app/cari/index'
import { Route as AnggotaEditPengukuranPengukuranIdRouteImport } from './app/anggota/edit-pengukuran/$pengukuranId'
import { Route as AnggotaEditEditIdRouteImport } from './app/anggota/edit/$editId'
import { Route as AnggotaInfoIdRouteImport } from './app/anggota/info/$id'
import { Route as AnggotaInputPesertaIdRouteImport } from './app/anggota/input/$pesertaId'
import { Route as AnggotaTambahIndexRouteImport } from './app/anggota/tambah/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunIndexRoute = AkunIndexRouteImport.update({
  id: '/akun/',
  path: '/akun/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIndexRoute = AnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => rootRouteImport,
} as any)
const CariIndexRoute = CariIndexRouteImport.update({
  id: '/cari/',
  path: '/cari/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaEditPengukuranPengukuranIdRoute =
  AnggotaEditPengukuranPengukuranIdRouteImport.update({
    id: '/anggota/edit-pengukuran/$pengukuranId',
    path: '/anggota/edit-pengukuran/$pengukuranId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnggotaEditEditIdRoute = AnggotaEditEditIdRouteImport.update({
  id: '/anggota/edit/$editId',
  path: '/anggota/edit/$editId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaInfoIdRoute = AnggotaInfoIdRouteImport.update({
  id: '/anggota/info/$id',
  path: '/anggota/info/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaInputPesertaIdRoute = AnggotaInputPesertaIdRouteImport.update({
  id: '/anggota/input/$pesertaId',
  path: '/anggota/input/$pesertaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaTambahIndexRoute = AnggotaTambahIndexRouteImport.update({
  id: '/anggota/tambah/',
  path: '/anggota/tambah/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akun/': typeof AkunIndexRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/cari/': typeof CariIndexRoute
  '/anggota/edit-pengukuran/$pengukuranId': typeof AnggotaEditPengukuranPengukuranIdRoute
  '/anggota/edit/$editId': typeof AnggotaEditEditIdRoute
  '/anggota/info/$id': typeof AnggotaInfoIdRoute
  '/anggota/input/$pesertaId': typeof AnggotaInputPesertaIdRoute
  '/anggota/tambah/': typeof AnggotaTambahIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akun': typeof AkunIndexRoute
  '/anggota': typeof AnggotaIndexRoute
  '/cari': typeof CariIndexRoute
  '/anggota/edit-pengukuran/$pengukuranId': typeof AnggotaEditPengukuranPengukuranIdRoute
  '/anggota/edit/$editId': typeof AnggotaEditEditIdRoute
  '/anggota/info/$id': typeof AnggotaInfoIdRoute
  '/anggota/input/$pesertaId': typeof AnggotaInputPesertaIdRoute
  '/anggota/tambah': typeof AnggotaTambahIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akun/': typeof AkunIndexRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/cari/': typeof CariIndexRoute
  '/anggota/edit-pengukuran/$pengukuranId': typeof AnggotaEditPengukuranPengukuranIdRoute
  '/anggota/edit/$editId': typeof AnggotaEditEditIdRoute
  '/anggota/info/$id': typeof AnggotaInfoIdRoute
  '/anggota/input/$pesertaId': typeof AnggotaInputPesertaIdRoute
  '/anggota/tambah/': typeof AnggotaTambahIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akun/'
    | '/anggota/'
    | '/cari/'
    | '/anggota/edit-pengukuran/$pengukuranId'
    | '/anggota/edit/$editId'
    | '/anggota/info/$id'
    | '/anggota/input/$pesertaId'
    | '/anggota/tambah/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akun'
    | '/anggota'
    | '/cari'
    | '/anggota/edit-pengukuran/$pengukuranId'
    | '/anggota/edit/$editId'
    | '/anggota/info/$id'
    | '/anggota/input/$pesertaId'
    | '/anggota/tambah'
  id:
    | '__root__'
    | '/'
    | '/akun/'
    | '/anggota/'
    | '/cari/'
    | '/anggota/edit-pengukuran/$pengukuranId'
    | '/anggota/edit/$editId'
    | '/anggota/info/$id'
    | '/anggota/input/$pesertaId'
    | '/anggota/tambah/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkunIndexRoute: typeof AkunIndexRoute
  AnggotaIndexRoute: typeof AnggotaIndexRoute
  CariIndexRoute: typeof CariIndexRoute
  AnggotaEditPengukuranPengukuranIdRoute: typeof AnggotaEditPengukuranPengukuranIdRoute
  AnggotaEditEditIdRoute: typeof AnggotaEditEditIdRoute
  AnggotaInfoIdRoute: typeof AnggotaInfoIdRoute
  AnggotaInputPesertaIdRoute: typeof AnggotaInputPesertaIdRoute
  AnggotaTambahIndexRoute: typeof AnggotaTambahIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/': {
      id: '/akun/'
      path: '/akun'
      fullPath: '/akun/'
      preLoaderRoute: typeof AkunIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/': {
      id: '/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AnggotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari/': {
      id: '/cari/'
      path: '/cari'
      fullPath: '/cari/'
      preLoaderRoute: typeof CariIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/edit-pengukuran/$pengukuranId': {
      id: '/anggota/edit-pengukuran/$pengukuranId'
      path: '/anggota/edit-pengukuran/$pengukuranId'
      fullPath: '/anggota/edit-pengukuran/$pengukuranId'
      preLoaderRoute: typeof AnggotaEditPengukuranPengukuranIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/edit/$editId': {
      id: '/anggota/edit/$editId'
      path: '/anggota/edit/$editId'
      fullPath: '/anggota/edit/$editId'
      preLoaderRoute: typeof AnggotaEditEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/info/$id': {
      id: '/anggota/info/$id'
      path: '/anggota/info/$id'
      fullPath: '/anggota/info/$id'
      preLoaderRoute: typeof AnggotaInfoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/input/$pesertaId': {
      id: '/anggota/input/$pesertaId'
      path: '/anggota/input/$pesertaId'
      fullPath: '/anggota/input/$pesertaId'
      preLoaderRoute: typeof AnggotaInputPesertaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/tambah/': {
      id: '/anggota/tambah/'
      path: '/anggota/tambah'
      fullPath: '/anggota/tambah/'
      preLoaderRoute: typeof AnggotaTambahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkunIndexRoute: AkunIndexRoute,
  AnggotaIndexRoute: AnggotaIndexRoute,
  CariIndexRoute: CariIndexRoute,
  AnggotaEditPengukuranPengukuranIdRoute:
    AnggotaEditPengukuranPengukuranIdRoute,
  AnggotaEditEditIdRoute: AnggotaEditEditIdRoute,
  AnggotaInfoIdRoute: AnggotaInfoIdRoute,
  AnggotaInputPesertaIdRoute: AnggotaInputPesertaIdRoute,
  AnggotaTambahIndexRoute: AnggotaTambahIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
